import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Image from "next/image";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="mx-auto w-full max-w-7xl px-4 py-6">
          <Link href="/">
            <div className="flex flex-col lg:flex-row items-center justify-center">
              <Image
                src="/nasa.svg"
                alt="nasa logo icon"
                width={150}
                height={20}
                style={{ marginRight: 15 }}
                priority
              />
              <h1 className="text-3xl font-bold">NASA Image and Video Library</h1>
            </div>
          </Link>
        </div>
        {children}
      </body>
    </html>
  );
}
